version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./server"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "./web"
    target-branch: "dev"
    schedule:
      interval: "weekly"
