version: "3"

services:
  nest:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest
    restart: unless-stopped
    environment:
      - DB_HOST=db
    env_file:
      - ./server/.env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    networks:
      - screamfeed_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    environment:
      - PORT=4200
      - PUBLIC_BASE_URL=http://localhost:3000/api
    ports:
      - "127.0.0.1:4200:4200"
    expose:
      - "4200"
    depends_on:
      - nest
    networks:
      - screamfeed_network

  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - "~/.local.docker/volumes/mariadb.backup:/var/lib/mysql:delegated"
    networks:
      - screamfeed_network

networks:
  screamfeed_network:
    driver: bridge
